### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pacpacpacpacpacpac** [Kagami/go-face#10]
GCC 7.3.0 , i get this error :

`go get github.com/Kagami/go-face`
command. 

```
# github.com/Kagami/go-face
In file included from /usr/include/dlib/matrix/matrix_conv.h:8:0,
                 from /usr/include/dlib/matrix.h:13,
                 from /usr/include/dlib/graph_utils/function_objects.h:7,
                 from /usr/include/dlib/graph_utils.h:8,
                 from classify.cc:1:
/usr/include/dlib/matrix/matrix_fft.h:12:10: fatal error: mkl_dfti.h: No such file or directory
 #include <mkl_dfti.h>
          ^~~~~~~~~~~~
compilation terminated.
```

Do you have an idea ?

**Comment by tpoxa** [comment]
@pacpacpacpacpacpac  which version of dlib you have?

**Comment by pacpacpacpacpacpac** [comment]
hum, ... version 19.10.0

**Comment by Kagami** [comment]
That's strange, because dlib in [PPA](https://launchpad.net/~kagamih/+archive/ubuntu/dlib) has 19.15 version.

**Comment by pacpacpacpacpacpac** [comment]
ok i will try to delete lib and download again, maybe i did mistakes

**Comment by pacpacpacpacpacpac** [comment]
Ok it's working, i haven't got problems anymore. 

My mistakes was i create /usr/local/lib/pkgconfig/dlib-1.pc

**Comment by silverark** [comment]
I've deleted that file, but I'm still getting the error. I'ver removed and installed dlib from the ppa without any luck.

**Comment by silverark** [comment]
> I've deleted that file, but I'm still getting the error. I'ver removed and installed dlib from the ppa without any luck.

I built dblib from scrath then added `// #cgo pkg-config: dlib-1` to the top of the face.go file whioch seems to now work. For some reason my Ubuntu 18.10 installation was installing libdlib-dev version 18. Couldn't update. When I used the PPA, it installed 19, but was missing the pkg-config.
