### ISSUE TITLE
mkl_dfti.h: No such file or directory

### ISSUE THREAD

**Issue by qburst-jerinjoseph** [Kagami/go-face#11]
Hi,
I have tried 
>> go get github.com/Kagami/go-face

 It gives me following error.

/usr/include/dlib/matrix/matrix_fft.h:12:22: fatal error: mkl_dfti.h: No such file or directory
compilation terminated.

From following link https://github.com/bakercp/ofxDlib/blob/master/docs/TROUBLESHOOTING.md
It is saying "Adjust your addons_config.mk file to include MKL."
But I can not find any addons_config.mk file. Can u guys help me out.

Thanks

**Comment by Kagami** [comment]
What's your operating system? How did you install dlib?

**Comment by qburst-jerinjoseph** [comment]
OS: Ubuntu 16.04
and dlib is downloaded using PPA

**Comment by Kagami** [comment]
Closing for now, please comment if that doesn't solve issue for you.
