### ISSUE TITLE
How to operate the fifth and sixth steps

### ISSUE THREAD

**Issue by fengweiqiang** [Kagami/go-face#12]
hello，
If you already have Go and Git installed and available in PATH uncomment set MSYS2_PATH_TYPE=inherit line in msys2_shell.cmd located in MSYS2 installation folder
Otherwise run pacman -S mingw-w64-x86_64-go git
Run MSYS2 MinGW 64-bit shell from Start menu to compile and use go-face

**Comment by fengweiqiang** [comment]
Hello, when running, error, system error, how to solve it?

This program cannot be started because the computer is missing libcblas.dll. Try to reinstall the program to resolve this issue.
![image](https://user-images.githubusercontent.com/22905300/49640097-9e48e700-fa47-11e8-8749-731a6f1e8276.png)

**Comment by fengweiqiang** [comment]
Microsoft Windows [VERSION 6.1.7601] 
Windows 7 64-bit Ultimate

**Comment by Kagami** [comment]
Hi. I haven't tried to compile with GoLand on Windows.
Try to run
```bash
mkdir -p ~/go && cd ~/go  # Or cd to your $GOPATH
mkdir -p src/go-face-example && cd src/go-face-example
git clone https://github.com/Kagami/go-face-testdata testdata
edit main.go  # Paste example code
go get && go run main.go
```
commands from MSYS2 MinGW 64-bit shell.

**Comment by Kagami** [comment]
Hope you get this working. Comment if something doesn't work for you with MinGW method.
