### ISSUE TITLE
Classifier always gives me some result 

### ISSUE THREAD

**Issue by SXerox007** [Kagami/go-face#16]
I try with two different images but it still return some id

**Comment by Kagami** [comment]
Try with higher tolerance.

**Comment by SXerox007** [comment]
I increased the tolerance small 0.8 then it always give the can't classify.

**Comment by SXerox007** [comment]
But both the images are same

**Comment by Kagami** [comment]
Please upload your test code and images.

**Comment by SXerox007** [comment]
`
	//TODO ---> Get the image url from db

	dataImage := filepath.Join(DATA_DIR, "mix.jpg")

	faces, err := rec.RecognizeFile(dataImage)
	if err != nil {
		return err
	}

	var samples []face.Descriptor
	var totalF []int32
	for i, f := range faces {
		samples = append(samples, f.Descriptor)
		// Each face is unique on that image so goes to its own category.
		totalF = append(totalF, int32(i))
	}

	// Pass samples to the recognizer.
	rec.SetSamples(samples, totalF)

	// Now let's try to classify some not yet known image.

	testData := filepath.Join(DATA_DIR, "sumit.jpg")
	res, err := [rec.RecognizeSingleFile(testData)](url)
	if err != nil {
		log.Println("Face not recorganise not the same person")
		return status.Errorf(
			codes.Internal,
			fmt.Sprintln(errormsg.ERR_FACE_NOT_REC))
	}
	if res == nil {
		log.Println("Not a sigle image")
		return status.Errorf(
			codes.Internal,
			fmt.Sprintln(errormsg.ERR_NOT_A_SINGLE_FACE))
	}
	id := rec.ClassifyThreshold(res.Descriptor, 0.6)
	if id < 0 {
		log.Println("Can't classify")
		return status.Errorf(
			codes.Internal,
			fmt.Sprintln(errormsg.ERR_MSG_INTERNAL_SERVER))
	}
	log.Println("id", id)
	log.Println("Image recorganise")

**Comment by SXerox007** [comment]
![eminem](https://user-images.githubusercontent.com/16977158/51181616-9e16f380-18f1-11e9-96df-83bf8ad26823.jpg)
![mix](https://user-images.githubusercontent.com/16977158/51181626-a66f2e80-18f1-11e9-883f-098b3574018d.jpg)
![sumit](https://user-images.githubusercontent.com/16977158/51181635-ad963c80-18f1-11e9-9d0a-6a4aab293a3e.jpg)

**Comment by SXerox007** [comment]
The three images I uploaded the first one named eminem.jpg 2nd one mix.jpg and 3rd one is sumit.jpg

**Comment by SXerox007** [comment]
Do you check @Kagami  ?

**Comment by Kagami** [comment]
Not yet, I will check a bit later.

**Comment by SXerox007** [comment]
Hi @Kagami  do you tell me when you will see this issue. ? Can you tell me what's the issue or something any hint !

**Comment by SXerox007** [comment]
Hi @Kagami have you seen this issue ?

**Comment by Kagami** [comment]
Hi, not yet, currently busy with other projects.

**Comment by vaizmanai** [comment]
it doesn't work completly, sadly...

**Comment by vaizmanai** [comment]
@SXerox007 hey, guy! I was written some functions for using with go-face and it works properly

`func compare_faces(samples []face.Descriptor, comp face.Descriptor, tolerance float32) int {
	res := face_distance(samples, comp)
	r := -1
	v := float32(1)

	for i, s := range res {
		t := euclidean_norm(s)
		if t < tolerance && t < v{
			v = t
			r = i
		}
	}

	return r
}

func face_distance(samples []face.Descriptor, comp face.Descriptor) []face.Descriptor {
	res := make([]face.Descriptor, len(samples))

	for i, s := range samples {
		for j, _ := range s {
			res[i][j] = samples[i][j] - comp[j]
		}
	}

	return res
}

func euclidean_norm(f face.Descriptor) float32 {
	var s float32
	for _, v := range f {
		s = s + v * v
	}

	return float32(math.Sqrt(float64(s)))
}`

You can call _compare_faces_ and it will return index of samples with the best matches but below set tolerance.

**Comment by SXerox007** [comment]
@vaizmanai not working.

**Comment by SXerox007** [comment]
Test with multiple images ,single image result is same. Not working.

**Comment by vaizmanai** [comment]
@SXerox007 i will check today at home and ping you

**Comment by vaizmanai** [comment]
@SXerox007 so it is working properly, i used your part of code, your test images, check youself: [test](https://github.com/vaizmanai/test_face)

**Comment by SXerox007** [comment]
Yes I test with many images use different images sometimes it works sometime it's not. See this [https://github.com/SXerox007/o2clock-Backend-](url)

**Comment by SXerox007** [comment]
@vaizmanai  I use the different images. id return some value if image is not even the same. I Snape the image form my phone and compare it will be return some value.

**Comment by vaizmanai** [comment]
Attach example photos with fails

**Comment by SXerox007** [comment]
@vaizmanai busy with some other things send you the example soon.

**Comment by SXerox007** [comment]
I found the problem when I give the static images file of different person then it will working fine as you said but when I compare with []bytes which will be coming from client side it will be returning some value. i.e rec.RecognizeSingle(image). I don't know why this happens but sometimes it work or sometime it not. So can you check this. why this will happens ? @vaizmanai

**Comment by Kagami** [comment]
I've fixed few bugs in `ClassifyThreshold`, please try with latest version from master.
