### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by shivamv** [Kagami/go-face#25]
I am constantly facing the error highlighted below, any help would be appreciated
OS: ubuntu 16.04

`
➜  ~ go get "github.com/Kagami/go-face"`
`gcc --version# github.com/Kagami/go-face
facerec.cc:103:7: error: ‘shared_mutex’ in namespace ‘std’ does not name a type
  std::shared_mutex samples_mutex_;`
       `^`
`facerec.cc: In member function ‘void FaceRec::SetSamples(std::vector<dlib::matrix<float, 0l, 1l> >&&, std::unordered_map<int, int>&&)’:
facerec.cc:91:20: error: ‘shared_mutex’ is not a member of ‘std’
   std::unique_lock<std::shared_mutex> lock(samples_mutex_);`

`➜  ~ gcc --version`
`gcc (Ubuntu 8.1.0-5ubuntu1~16.04) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

**Comment by Kagami** [comment]
That's strange, your gcc version looks fine.

Does this work:

```cpp
#include <stdio.h>
#include <mutex>
#include <shared_mutex>

int main() {
  std::shared_mutex mutex;
  std::unique_lock<std::shared_mutex> lock(mutex);
  printf("test\n");
  return 0;
}
```

```bash
g++ -std=c++1z -lpthread -o 1 1.cc
```

If not, maybe try install gcc 8.2.0/8.3.0/7.3.0/7.4.0. Also, make sure `g++ --version` is fine too.
Do you use environment variables like `CXX` by any chance?

**Comment by shivamv** [comment]
@Kagami thanks for a prompt response

my g++ version(5.4) wasn't consistent with the gcc version, got it fixed.
Thanks :+1:
