### ISSUE TITLE
undefined face functions

### ISSUE THREAD

**Issue by GOOD-Stuff** [Kagami/go-face#29]
Hi! 
First of all, I am appreciate your project, it's very helpful.
But after installing all dependencies (dlib, openblas, etc) and trying to repeat your example, I catch next errors (and in ```make test``` too):
```
./main.go:19:14: undefined: face.NewRecognizer
./main.go:40:16: undefined: face.Descriptor
```
I tried set alias for package (```import alias_name "github.com/Kagami/go-face"```) but it doesn't help.
I'm newby in golang, and may set wrong GOPATH settings, but my every try with different of them catch this errors.
Golang paths which I tried setup:
``` 
GOROOT = $HOME/Programs/go 
1) GOPATH = $HOME/Programs/go
2) GOPATH = $HOME/projects/Go/project_names/
3) GOPATH = $HOME/go
```
The funny thing is that GoLand saw package, doesn't show them as error and I can move on it.
Work under XUbuntu 16.04, GoLand 2018.3, Go 1.11.4.

P.S. Excuse me for dummy question and not well english.

**Comment by Kagami** [comment]
Try these steps:

```
export GOPATH=$HOME/go
mkdir -p $HOME/go/src/go-face-example
cd $HOME/go/src/go-face-example
git clone https://github.com/Kagami/go-face-testdata testdata
wget https://gist.github.com/Kagami/887ad63fe9182f00e94ab14943500982/raw/74653be9192be1df17cd257bb8ca0ba2e7413d20/main.go
go get
go run main.go
```

**Comment by GOOD-Stuff** [comment]
HI! 
Thank you for responsive. 
I tried your instruction on home machine with Ubuntu 18.04, and here it's work! 
I will try tomorrow it on working machine.

**Comment by GOOD-Stuff** [comment]
Good day!
After updating gcc and reinstalling libs, your example works!
Thanks for help!
