### ISSUE TITLE
Unclear variable use in classify.cc

### ISSUE THREAD

**Issue by dzon93** [Kagami/go-face#31]
Hi,

I'm struggling to understand a part of your code in classify.cc, I kind of understand how the whole process works, but I don't understand what is idxs variable used for.
To be precise, lines 16 through 23:

	int idx = 0;
	for (const auto& sample : samples) {
		float dist = dist_func(sample, test_sample);
		if (dist < tolerance)
			continue;
		distances.push_back({idx, dist});
		idx++;
	}

You're iterating through individual samples (or face vectors, whatever) and comparing the distance between a test_sample and each sample in our collection. What I don't understand is why you push and increase idx if distance is less than tolerance. How does idxs correlate to category index?

**Comment by bbars** [comment]
There would be a a shift. idx normally should be increased at the beginning of iteration, I think.

**Comment by Kagami** [comment]
Yes, it's a bug introduced by 4d258ca248c2e7c45284836bf8e032b9defaae19
`idx` should correspond to category's sequential index, being calculated in https://github.com/Kagami/go-face/blob/84d557bef326aed73fd8f41820b681dbe7e48427/facerec.cc#L183

I've pushed a fix. Thank you @dzon93 @bbars for the report.
