### ISSUE TITLE
CNN Face Detector

### ISSUE THREAD

**Issue by agorman** [Kagami/go-face#34]
Hey Kagami,

Any plans to make the CNN face detector from dlib available though this package?

http://dlib.net/dnn_mmod_face_detection_ex.cpp.html

Thanks!

**Comment by Kagami** [comment]
Currently no, but PR would be nice.

**Comment by Danile71** [comment]
I added CNN, now I will make pull request.

**Comment by Kagami** [comment]
Thanks @Danile71, closing this in favor of #35.
