### ISSUE TITLE
only Recognizer jpeg image,can't support png 

### ISSUE THREAD

**Issue by foreachsky** [Kagami/go-face#48]
hi ,i user opencv to detect the face regoin,then use go-face to recognizer ,i put []byte to call Recognize() function,but it's error:
jpeg_mem_loader: decode error: Not a JPEG file: starts with 0x75 0x93

**Comment by tpoxa** [comment]
So yes, only JPEG format supported currently.

**Comment by Kagami** [comment]
Duplicate of #45
