### ISSUE TITLE
GitHub.com/Kagami/go-face

### ISSUE THREAD

**Issue by shivesh86** [Kagami/go-face#49]
Facing below issue:

# github.com/Kagami/go-face
../../pkg/mod/github.com/!kagami/go-face@v0.0.0-20180922080525-863b26a6405e/face.go:25:7: identifier "_Ctype_struct_facerec" may conflict with identifiers generated by cgo

Go Version : 1.14.2
Mac OS : 10.15.4

**Comment by Kagami** [comment]
Duplicate of #47
