### ISSUE TITLE
Windows 7/10 build errors

### ISSUE THREAD

**Issue by MsZako** [Kagami/go-face#52]
Greetings! I can’t assemble the go-face, everything is done according to the instructions and on Win7 and 10 it produces the same error:

###@##### MSYS ~/go-face
$ go build
/C_/msys64/home/###/go-face
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\_\C_\msys64\home\DEZ\go-face\_obj\facerec.cc.o: in function dlib::blas_bindings::cblas_gemm(dlib::blas_bindings::CBLAS_ORDER, dlib::blas_bindings::CBLAS_TRANSPOSE, dlib::blas_bindings::CBLAS_TRANSPOSE, int, int, int, double, double const*, int, double const*, int, double, double*, int):
C:/msys64/home/DEZ/go-face/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to cblas_dgemm
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/DEZ/go-face/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to cblas_dgemm
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/DEZ/go-face/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to cblas_dgemm
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/DEZ/go-face/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to cblas_dgemm
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\_\C_\msys64\home\DEZ\go-face\_obj\facerec.cc.o: in function dlib::blas_bindings::cblas_scal(int, float, float*):
C:/msys64/home/DEZ/go-face/dlib/matrix/matrix_blas_bindings.h:177: undefined reference to cblas_sscal
collect2.exe: error: ld returned 1 exit status

If it does not bother you, tell me, please, a solution. Thank!

**Comment by zenthangplus** [comment]
I've same problems. Please help. Thanks

```
$ go build .
# github.com/Kagami/go-face
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b037\_x005.o: in function `dlib::blas_bindings::cblas_gemm(dlib::blas_bindings::CBLAS_ORDER, dlib::blas_bindings::CBLAS_TRANSPOSE, dlib::blas_bindings::CBLAS_TRANSPOSE, int, int, int, double, double const*, int, double const*, int, double, double*, int)':
C:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to `cblas_dgemm'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to `cblas_dgemm'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b037\_x005.o: in function `dlib::blas_bindings::matrix_assign_blas_helper<dlib::matrix<double, 2l, 3l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>, dlib::matrix_multiply_exp<dlib::matrix<double, 2l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>, dlib::matrix<double, 0l, 3l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> >, void>::assign(dlib::matrix<double, 2l, 3l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>&, dlib::matrix_multiply_exp<dlib::matrix<double, 2l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>, dlib::matrix<double, 0l, 3l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> > const&, double, bool, bool)':
C:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to `cblas_dgemm'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b037\_x005.o: in function `dlib::blas_bindings::cblas_gemm(dlib::blas_bindings::CBLAS_ORDER, dlib::blas_bindings::CBLAS_TRANSPOSE, dlib::blas_bindings::CBLAS_TRANSPOSE, int, int, int, double, double const*, int, double const*, int, double, double*, int)':
C:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to `cblas_dgemm'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b037\_x005.o: in function `dlib::blas_bindings::cblas_scal(int, float, float*)':
C:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:177: undefined reference to `cblas_sscal'
collect2.exe: error: ld returned 1 exit status

```

**Comment by xzzh999** [comment]
these are link errors about blas , u can try to use http://icl.cs.utk.edu/lapack-for-windows/lapack/ prebuild libs, or try OpenBLAS.

**Comment by spetr** [comment]
You must build it with these CGO flags:

SET CGO_LDFLAGS=-LC:\tools\msys64\mingw64\include\OpenBLAS -lopenblas
go build

**Comment by Yedrops** [comment]
win10 msys2
`
pc@DESKTOP-S5EB67I MINGW64 /d/web/recognize/third_party/go-face (master)
$ go build
# github.com/Kagami/go-face
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b001\_x005.o: in function `dlib::blas_bindings::cblas_gemm(dlib::blas_bindings::CBLAS_ORDER, dlib::blas_bindings::CBLAS_TRANSPOSE, dlib::blas_bindings::CBLAS_TRANSPOSE, int, int, int, double, double const*, int, double const*, int, double, double*, int)':
D:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to `cblas_dgemm'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to `cblas_dgemm'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to `cblas_dgemm'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to `cblas_dgemm'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b001\_x005.o: in function `dlib::blas_bindings::cblas_scal(int, float, float*)':
D:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:177: undefined reference to `cblas_sscal'
`

**Comment by Yedrops** [comment]
> win10 msys2 go build or go get
> 
> ```
> D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b001\_x005.o: in function `dlib::blas_bindings::cblas_gemm(dlib::blas_bindings::CBLAS_ORDER, dlib::blas_bindings::CBLAS_TRANSPOSE, dlib::blas_bindings::CBLAS_TRANSPOSE, int, int, int, double, double const*, int, double const*, int, double, double*, int)':
> D:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to `cblas_dgemm'
> D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to `cblas_dgemm'
> D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to `cblas_dgemm'
> D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to `cblas_dgemm'
> D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b001\_x005.o: in function `dlib::blas_bindings::cblas_scal(int, float, float*)':
> D:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:177: undefined reference to `cblas_sscal'
> collect2.exe: error: ld returned 1 exit status
> ```


---------------------------------------------------------------------------------------------------------------
mkdir recognize

cd recognize

go mod init recognize

mkdir third_party

cd third_party

git clone https://github.com/Kagami/go-face.git
git clone https://github.com/Kagami/go-face-testdata.git

edit third_party/go-face/face.go

old

```
package face

// #cgo CXXFLAGS: -std=c++1z -Wall -O3 -DNDEBUG -march=native
// #cgo LDFLAGS: -ldlib -lblas -llapack -ljpeg
// #include <stdlib.h>
// #include <stdint.h>
// #include "facerec.h"
```

change

```
package face

// #cgo CXXFLAGS: -std=c++1z -Wall -O3 -DNDEBUG -march=native
// #cgo LDFLAGS: -L D:\msys64\mingw64\include\OpenBLAS -lopenblas -ldlib -lblas -llapack -ljpeg
// #include <stdlib.h>
// #include <stdint.h>
// #include "facerec.h"
```

```
cd third_party/go-face
go build
```

go.mod

```
module recognize

go 1.14

require github.com/Kagami/go-face v0.0.0-20200825065730-3dd2d74dccfb

replace github.com/Kagami/go-face => ./third_party/go-face
```

main.go

```
package main

import (
	"fmt"
	"log"

	"github.com/Kagami/go-face"
)

// Path to directory with models and test images. Here it's assumed it
// points to the <https://github.com/Kagami/go-face-testdata> clone.
// const dataDir = "D:/web/recognize"

var (
	modelsDir = "D:/web/recognize/third_party/go-face-testdata/models"
	imagesDir = "D:/web/recognize/third_party/go-face-testdata/images"
)

// This example shows the basic usage of the package: create an
// recognizer, recognize faces, classify them using few known ones.
func main() {
	// Init the recognizer.
	rec, err := face.NewRecognizer(modelsDir)
	if err != nil {
		log.Fatalf("Can't init face recognizer: %v", err)
	}
	// Free the resources when you're finished.
	defer rec.Close()

	// Test image with 10 faces.
	testImagePristin := imagesDir+"/pristin.jpg"
	// Recognize faces on that image.
	faces, err := rec.RecognizeFile(testImagePristin)
	if err != nil {
		log.Fatalf("Can't recognize: %v", err)
	}
	if len(faces) != 10 {
		log.Fatalf("Wrong number of faces")
	}

	// Fill known samples. In the real world you would use a lot of images
	// for each person to get better classification results but in our
	// example we just get them from one big image.
	var samples []face.Descriptor
	var cats []int32
	for i, f := range faces {
		samples = append(samples, f.Descriptor)
		// Each face is unique on that image so goes to its own category.
		cats = append(cats, int32(i))
	}
	// Name the categories, i.e. people on the image.
	labels := []string{
		"Sungyeon", "Yehana", "Roa", "Eunwoo", "Xiyeon",
		"Kyulkyung", "Nayoung", "Rena", "Kyla", "Yuha",
	}
	// Pass samples to the recognizer.
	rec.SetSamples(samples, cats)

	// Now let's try to classify some not yet known image.
	testImageNayoung :=imagesDir+"/nayoung.jpg"
	nayoungFace, err := rec.RecognizeSingleFile(testImageNayoung)
	if err != nil {
		log.Fatalf("Can't recognize: %v", err)
	}
	if nayoungFace == nil {
		log.Fatalf("Not a single face on the image")
	}
	catID := rec.Classify(nayoungFace.Descriptor)
	if catID < 0 {
		log.Fatalf("Can't classify")
	}
	// Finally print the classified label. It should be "Nayoung".
	fmt.Println(labels[catID])
}
```

```
go run main.go

output
Nayoung
```

**Comment by Yedrops** [comment]
> Greetings! I can’t assemble the go-face, everything is done according to the instructions and on Win7 and 10 it produces the same error:
> 
> ###@##### MSYS ~/go-face
> $ go build
> /C_/msys64/home/###/go-face
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK_\C_\msys64\home\DEZ\go-face_obj\facerec.cc.o: in function dlib::blas_bindings::cblas_gemm(dlib::blas_bindings::CBLAS_ORDER, dlib::blas_bindings::CBLAS_TRANSPOSE, dlib::blas_bindings::CBLAS_TRANSPOSE, int, int, int, double, double const*, int, double const*, int, double, double*, int):
> C:/msys64/home/DEZ/go-face/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to cblas_dgemm
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/DEZ/go-face/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to cblas_dgemm
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/DEZ/go-face/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to cblas_dgemm
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/DEZ/go-face/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to cblas_dgemm
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK_\C_\msys64\home\DEZ\go-face_obj\facerec.cc.o: in function dlib::blas_bindings::cblas_scal(int, float, float*):
> C:/msys64/home/DEZ/go-face/dlib/matrix/matrix_blas_bindings.h:177: undefined reference to cblas_sscal
> collect2.exe: error: ld returned 1 exit status
> 
> If it does not bother you, tell me, please, a solution. Thank!

I've worked it out

**Comment by MsZako** [comment]
Many thanks to all! Everything worked out.
