### ISSUE TITLE
Instruction seems not right for MacOS High Serra

### ISSUE THREAD

**Issue by ajeecai** [Kagami/go-face#6]
MacOS High Serra 10.13.4， 
$ sed -i 's/^Libs: .*/& -lblas -llapack/' /usr/local/lib/pkgconfig/dlib-1.pc
sed: 1: "/usr/local/lib/pkgconfi ...": extra characters at the end of l command

$ go run main.go 
#pkg-config --cflags dlib-1
pkg-config: exec: "pkg-config": executable file not found in $PATH

The solution is : 
$ brew install pkg-config
After that it works. 

Thanks

**Comment by Kagami** [comment]
Fixed, thanks!
I've seen you had additional question, is it still relevant?

**Comment by ajeecai** [comment]
The additional question, at beginning I had thought jpgs in testdata are the training data. But I get the point later (maybe I am wrong, though), the model has been trained by dlib, the result are dlib_face_recognition_resnet_model_v1.dat and shape_predictor_5_face_landmarks.dat. The project is only using the final model, not trained from the jpgs from scratch, the jpgs only keep here for our testing its validation.  Just for fun, I download http://asianwiki.com/images/2/29/Kang_Sung-Yeon-p5.jpg and but it is recognized as Nayoung :)

**Comment by Kagami** [comment]
Yes, you're right.

>but it is recognized as Nayoung

I guess among 10 faces from pristin.jpg (if you used the example) her face is closest to Nayoung :)
