### ISSUE TITLE
queued-like *face.Recognizer

### ISSUE THREAD

**Issue by codenoid** [Kagami/go-face#63]
i use global *face.Recognizer for concurrent use, but i notice a strange issue, which *face.Recognizer likely execute in queued order

![Screenshot from 2020-11-17 04-55-14](https://user-images.githubusercontent.com/14269809/99312956-5d8fb480-2891-11eb-88f1-f2a66dec0e40.png)

the execution time increase by how many concurrent call to *face.Recognizer

**Comment by rudved** [comment]
C:\Users\Lenovo\go\src>go get github.com/leandroveronezi/go-recognizer
# github.com/Kagami/go-face
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b048\_x005.o: in function `dlib::blas_bindings::cblas_gemm(dlib::blas_bindings::CBLAS_ORDER, dlib::blas_bindings::CBLAS_TRANSPOSE, dlib::blas_bindings::CBLAS_TRANSPOSE, int, int, int, double, double const*, int, double const*, int, double, double*, int)':
C:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to `cblas_dgemm'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to `cblas_dgemm'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to `cblas_dgemm'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:218: undefined reference to `cblas_dgemm'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b048\_x005.o: in function `dlib::blas_bindings::cblas_scal(int, float, float*)':
C:/msys64/mingw64/include/dlib/matrix/matrix_blas_bindings.h:177: undefined reference to `cblas_sscal'
collect2.exe: error: ld returned 1 exit status

**Comment by rudved** [comment]
Im getting this error plz tell me if you have any solution i have don this in windows
