### ISSUE TITLE
Threshold

### ISSUE THREAD

**Issue by tpoxa** [Kagami/go-face#9]
Is there any way to set up minimal threshold, cause now classifier always gives me some result even if I try with absolutely different face

Thanks

**Comment by Kagami** [comment]
Currently not possible but that option should be useful and worth to implement.

**Comment by tpoxa** [comment]
Hi @Kagami, any updates? Can you maybe target me how to do this by myself. Thanks.

**Comment by Kagami** [comment]
I'll try to look into this soon.

**Comment by tpoxa** [comment]
And it will not be superfluous to say than lower threshold than more strict recognition.
